### ISSUE TITLE
 Social media icon don't redirect to your social media accounts

### ISSUE THREAD

**Issue by pangilinanervin22** [LueKely/ToDoWithVue#3]

**Comment by LueKely** [comment]
This was done purposely so for I do not want to doxx myself it was there for visual flare

**Comment by Jiseeeh** [comment]
@pangilinanervin22 is a *troll*

**Comment by LueKely** [comment]
Sussy baka amogis imposter sus fortnite

**Comment by LueKely** [comment]
> @pangilinanervin22 is a *troll*

Sussy baka amogus imposter sus stole my victory royale fortnite default dance i told you long ago ~
